"""
Django settings for MacQuest_Serverside project.

Generated by 'django-admin startproject' using Django 2.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '3)=k=lz$70fu!*n5ru)-_$bw3j--4#yc_1v2zn6cfj6@_szd+*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Accounts',
    'MacQuest',
    'MacQuestData',
    'SmartSearch',
    'EventManage',
    'EventAPI',
    'rest_framework'

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MacQuest_Serverside.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MacQuest_Serverside.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Canada/Eastern'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
# 开发阶段放置项目自己的静态文件

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)

#STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

WHOOSH_INDEX_ROOM_BUILDING = "BuildingIndex"

WHOOSH_INDEX_EVENT = "EventIndex"

WHOOSH_INDEX_PARENTEVENT_NAME = "parentEventIndex"
WHOOSH_INDEX_SUBEVENTNAME_NAME = "subEventIndex"

# Account module setting
AUTH_USER_MODEL = 'Accounts.User'
LOGOUT_REDIRECT_URL = '/'
LOGIN_REDIRECT_URL = '/'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'Accounts.backends.EmailBackend',
)

# EMAIL Settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_USE_SSL = True
EMAIL_USE_TLS = False
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'zerone.jia@gmail.com'
EMAIL_HOST_PASSWORD = 'Sat2009google'
DEFAULT_FROM_EMAIL = 'zerone.jia@gmail.com'

ADMIN_EMAIL = 'zerone.jia@gmail.com'
SENDING_EMAIL = 'zerone.jia@gmail.com'

# Register email settings
EMAIL_REGISTER_SUBJECT = "New user registered in MacQuest Event Website."
EMAIL_REGISTER_TEMPLATE_PATH_TEXT = "Accounts/email_template/register_admin_email_text.txt"
EMAIL_REGISTER_TEMPLATE_PATH_HTML = "Accounts/email_template/register_admin_email_html.html"

# Activate user email settings.
EMAIL_USER_ACTIVATE_SUBJECT = "Your account is activated by Admin on MacQuest Website"
EMAIL_USER_ACTIVATE_TEMPLATE_PATH_TEXT = "Accounts/email_template/user_activate_email_text.txt"
EMAIL_USER_ACTIVATE_TEMPLATE_PATH_HTML = "Accounts/email_template/user_activate_email_html.html"

WEBSITE_DOMAIN = "127.0.0.1:8000"
LOGIN_URL = "http://" + WEBSITE_DOMAIN + "/" + "accounts/login"

