/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package com.mcmaster.wiser.idyll;

public final class Manifest {
  public static final class permission {
    public static final String SEND_LOCATION="com.mcmaster.wiser.idyll.SEND_LOCATION";
    public static final String C2D_MESSAGE="com.mcmaster.wiser.idyll.permission.C2D_MESSAGE";
  }
  public static final class permission_group {
    public static final String SERVER="android.permission-group.SERVER";
  }
}