# Generated by Django 2.1.4 on 2018-12-09 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buildingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outid', models.TextField()),
                ('showname', models.TextField()),
                ('st_astext', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='roomsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.TextField(null=True)),
                ('outid', models.TextField(null=True)),
                ('name', models.TextField(null=True)),
                ('utility', models.TextField(null=True)),
                ('floor', models.TextField(null=True)),
                ('location', models.TextField(null=True)),
                ('nearsetStaircase', models.TextField(null=True)),
                ('nearestElevator', models.TextField(null=True)),
                ('geometry', models.TextField(null=True)),
                ('buildingName', models.TextField(null=True)),
                ('centroid', models.TextField(null=True)),
                ('shortName', models.TextField(null=True)),
                ('buildingCenter', models.TextField(null=True)),
            ],
        ),
    ]
